# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghostenv < Formula
  desc "Keep secrets away from AI agents"
  homepage "https://github.com/Rituraj003/ghostenv"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Rituraj003/ghostenv/releases/download/v0.1.0/ghostenv_0.1.0_darwin_amd64.tar.gz"
      sha256 "d625ae9e7ef125dc47ae2e9a98e6d4b253ea0d6d405603db9539a4464f5becf5"

      define_method(:install) do
        bin.install "ghostenv"
        bin.install "ghostenv-keychain" if File.exist? "ghostenv-keychain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Rituraj003/ghostenv/releases/download/v0.1.0/ghostenv_0.1.0_darwin_arm64.tar.gz"
      sha256 "386d55de54030868d824c4a13f0efc4e111e0405524ff1ff1921652aedf6028b"

      define_method(:install) do
        bin.install "ghostenv"
        bin.install "ghostenv-keychain" if File.exist? "ghostenv-keychain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rituraj003/ghostenv/releases/download/v0.1.0/ghostenv_0.1.0_linux_amd64.tar.gz"
      sha256 "c54c8452e53ba589af78bfc386ad2f0dbd5bcc70725b4a3d923bb7cc1877c529"
      define_method(:install) do
        bin.install "ghostenv"
        bin.install "ghostenv-keychain" if File.exist? "ghostenv-keychain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rituraj003/ghostenv/releases/download/v0.1.0/ghostenv_0.1.0_linux_arm64.tar.gz"
      sha256 "b3a05b59ffa18db7935a35d11ebcd204b711db36acec823639e5a2363e33b08c"
      define_method(:install) do
        bin.install "ghostenv"
        bin.install "ghostenv-keychain" if File.exist? "ghostenv-keychain"
      end
    end
  end
end
