# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghostenv < Formula
  desc "Keep secrets away from AI agents"
  homepage "https://github.com/Rituraj003/ghostenv"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Rituraj003/ghostenv/releases/download/v0.1.0/ghostenv_0.1.0_darwin_amd64.tar.gz"
      sha256 "b45d4bc6c6ed37643c42af785b97d84e02097b5e17a5d76ba4913180e90c5579"

      define_method(:install) do
        bin.install "ghostenv"
        bin.install "ghostenv-mcp"
        bin.install "ghostenv-keychain" if File.exist? "ghostenv-keychain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Rituraj003/ghostenv/releases/download/v0.1.0/ghostenv_0.1.0_darwin_arm64.tar.gz"
      sha256 "3c469900f6acc7828de6c474473c455065b3a5e99fb52fea9c91cf4ee8efe963"

      define_method(:install) do
        bin.install "ghostenv"
        bin.install "ghostenv-mcp"
        bin.install "ghostenv-keychain" if File.exist? "ghostenv-keychain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rituraj003/ghostenv/releases/download/v0.1.0/ghostenv_0.1.0_linux_amd64.tar.gz"
      sha256 "0fb3c2b5a4e761ae6bdb375c1369287090bd51d1c61ec20d1b0e4f47ed861069"
      define_method(:install) do
        bin.install "ghostenv"
        bin.install "ghostenv-mcp"
        bin.install "ghostenv-keychain" if File.exist? "ghostenv-keychain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rituraj003/ghostenv/releases/download/v0.1.0/ghostenv_0.1.0_linux_arm64.tar.gz"
      sha256 "7be83395f40d296f68ee7bd5a357d55e7fde89a0a4180310eb7ad1356a8c46ea"
      define_method(:install) do
        bin.install "ghostenv"
        bin.install "ghostenv-mcp"
        bin.install "ghostenv-keychain" if File.exist? "ghostenv-keychain"
      end
    end
  end
end
