# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghostenv < Formula
  desc "Keep secrets away from AI agents"
  homepage "https://github.com/Rituraj003/ghostenv"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Rituraj003/ghostenv/releases/download/v0.1.0/ghostenv_0.1.0_darwin_amd64.tar.gz"
      sha256 "60ff2e16884607c4ad06f62338fa51c6c3792bfd18f17850060d7f2fcf138d85"

      define_method(:install) do
        bin.install "ghostenv"
        bin.install "ghostenv-keychain" if File.exist? "ghostenv-keychain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Rituraj003/ghostenv/releases/download/v0.1.0/ghostenv_0.1.0_darwin_arm64.tar.gz"
      sha256 "ed944cf49b41c9b0df2d72a3a7442a6375297e274cbf2da2d175f3bcbe671c55"

      define_method(:install) do
        bin.install "ghostenv"
        bin.install "ghostenv-keychain" if File.exist? "ghostenv-keychain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rituraj003/ghostenv/releases/download/v0.1.0/ghostenv_0.1.0_linux_amd64.tar.gz"
      sha256 "23b9cf46c17be1f0dac8a1994d9c1a00481dc8c7640fd368b0e6cd59f92695dc"
      define_method(:install) do
        bin.install "ghostenv"
        bin.install "ghostenv-keychain" if File.exist? "ghostenv-keychain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rituraj003/ghostenv/releases/download/v0.1.0/ghostenv_0.1.0_linux_arm64.tar.gz"
      sha256 "a6f7e2393a8c56650f5fd477c7e05bcb43a41ef6b2ea0adf20464cb3b9d37450"
      define_method(:install) do
        bin.install "ghostenv"
        bin.install "ghostenv-keychain" if File.exist? "ghostenv-keychain"
      end
    end
  end
end
